name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    name: "CI Job"
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.2.2
    - name: Autenticação no docker hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    













    
      - name: "Minha primeira action"
        run: echo "Hello World !!!"
      - name: "Segunda action"
        run: |
          echo "Você criou seu primeiro Workflow !!!"
          echo "Parabéns !!!"
      - name: "Verificação da versão do Python"
        run: python --version    
      - name: "Script Python"
        run: |
          variavel = "Hello Python!!"
          print(variavel)
        shell: python

  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 20.13.1 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: "NOVA Verificação da versão do NodeJS atual"
        run: node --version
